version: "3.8"

services:
  app:
    build:
      target: deps
    environment:
      - NODE_ENV=test
      - MONGODB_URI=mongodb://mongodb:27017/blogbuster_test
      - LOG_LEVEL=error
    command: npm run test
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  mongodb:
    ports:
      - "27018:27017" # Different port to avoid conflicts with dev
    volumes:
      - mongodb_test_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

volumes:
  mongodb_test_data:
