services:
  app:
    environment:
      - NODE_ENV=test
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/blogbuster_test?authSource=admin
      - LOG_LEVEL=error
    command: npm run test
    ports:
      - "3001:3000"

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_test_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - blogbuster-network

volumes:
  mongodb_test_data:

networks:
  blogbuster-network:
    driver: bridge
