version: "3.8"

services:
  app:
    build:
      target: deps
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/blogbuster
      - LOG_LEVEL=debug
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  mongodb:
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

volumes:
  mongodb_data:
