services:
  app:
    environment:
      - NODE_ENV=test
      - MONGODB_URI=${MONGODB_URI_TEST:-mongodb://admin:password@mongodb:27017/blogbuster_test?authSource=admin}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - LOG_LEVEL=error
    command: npm run test
    ports:
      - "3001:3000"

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_test_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    networks:
      - blogbuster-network

volumes:
  mongodb_test_data:

networks:
  blogbuster-network:
    driver: bridge
